services:
  predictif-production:
    build: .
    container_name: predictif-production
    expose:
      - 3000
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
    volumes:
      - ./datasets:/app/datasets
    networks:
      - traefik_public
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.predictif-production.rule=Host(`predictif-mcp.adrienpelfresne.com`)"
      - "traefik.http.routers.predictif-production.tls=true"
      - "traefik.http.routers.predictif-production.entrypoints=web,websecure"
      - "traefik.http.routers.predictif-production.tls.certresolver=letsencrypt"
      - "traefik.http.services.predictif-production.loadbalancer.server.port=3000"

networks:
  traefik_public:
    external: true
