services:
  predictif:
    build: .
    container_name: predictif-mcp
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.predictif_mcp-staging.rule=Host(`predictif.adrienpelfresne.com`)"
      - "traefik.http.routers.predictif_mcp-staging.tls=true"
      - "traefik.http.routers.predictif_mcp-staging.entrypoints=web,websecure"
      - "traefik.http.routers.predictif_mcp-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.predictif_mcp-staging.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
